;/*FB_PKG_DELIM*/

__d("GroupsCometColorWrapper_group.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"GroupsCometColorWrapper_group",selections:[{alias:null,args:null,concreteType:"Group",kind:"LinkedField",name:"if_viewer_can_see_expanded_color",plural:!1,selections:[{args:null,documentName:"GroupsCometColorWrapper_group_canSeeExpandedColor",fragmentName:"GroupsCometColorExpandedWrapper_group",fragmentPropName:"group",kind:"ModuleImport"}],storageKey:null},{alias:null,args:null,concreteType:"Group",kind:"LinkedField",name:"if_viewer_cannot_see_expanded_color",plural:!1,selections:[{args:null,documentName:"GroupsCometColorWrapper_group_cannotSeeExpandedColor",fragmentName:"GroupsCometColorDefaultWrapper_group",fragmentPropName:"group",kind:"ModuleImport"}],storageKey:null}],type:"Group",abstractKey:null};e.exports=a}),null);
__d("NullStateLists",["cr:3212"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:3212")}),98);
__d("NullStateListsFB",["IconSource"],(function(a,b,c,d,e,f,g){"use strict";a={dark:new(c("IconSource"))("nullStateGlyphs","/images/comet/empty_states_icons/lists/null_states_list_dark_mode.svg",112),"default":new(c("IconSource"))("nullStateGlyphs","/images/comet/empty_states_icons/lists/null_states_list_gray_wash.svg",112)};g["default"]=a}),98);
__d("GroupsCometCreatePreviewContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b={isPreview:!1};c=a.createContext(b);g["default"]=c}),98);
__d("GroupsCometCreatePreviewDisabledWrapper.react",["GroupsCometCreatePreviewContext","react","useCurrentDisplayMode"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react"),i=d("react").useContext;function a(a){var b=a.children;a=a.hasPreviewData;a=a===void 0?!1:a;var d=c("useCurrentDisplayMode")()==="dark",e=i(c("GroupsCometCreatePreviewContext"));e=e.isPreview;e=e===void 0?!1:e;return h.jsx("div",{className:""+(e&&!a&&!d?" x1e0x9i4":""+(e&&!a&&d?" xy712c7":"")),children:b})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("GroupsCometColorWrapper.react",["CometRelay","GroupsCometColorWrapper_group.graphql","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=d("react");function a(a){var c=a.children,e=a.group,f=a.isDefaultColorApplied;f=f===void 0?!0:f;var g=a.properties;a=a.testid;e=d("CometRelay").useFragment(h!==void 0?h:h=b("GroupsCometColorWrapper_group.graphql"),e);if((e==null?void 0:e.if_viewer_can_see_expanded_color)!=null)return i.jsx(d("CometRelay").MatchContainer,{match:e==null?void 0:e.if_viewer_can_see_expanded_color,props:{children:c,properties:g,testid:a}});return(e==null?void 0:e.if_viewer_cannot_see_expanded_color)&&f?i.jsx(d("CometRelay").MatchContainer,{match:e.if_viewer_cannot_see_expanded_color,props:{children:c,testid:a}}):c}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("GroupsCometPersistentJoinedStatusAvailabilityContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext(!1);g["default"]=b}),98);
__d("usePreviousSurfaceForGroupLogging",["useRoutePassthroughProps","useRouteReferrer"],(function(a,b,c,d,e,f,g){"use strict";function a(){var a=c("useRoutePassthroughProps")(),b=c("useRouteReferrer")();switch(a==null?void 0:a.ref){case"community_panel":return"community_panel";case"feed_story":case"actor_hovercard":if((b==null?void 0:b.tracePolicy)==="comet.groups.feed")return"groups_targeted_tab";else if((b==null?void 0:b.tracePolicy)==="comet.home")return"newsfeed";else if((b==null?void 0:b.tracePolicy)==="comet.profile.collection.groups")return"timeline";else return"unknown";case"your_groups":return"other";case"groups_card":if((b==null?void 0:b.tracePolicy)==="comet.groups.discover")return"groups_discover_tab";else if((b==null?void 0:b.tracePolicy)==="comet.home")return"gysj";else return"unknown";case"notification":return"notification";case"bookmark":return"bookmarks";default:return"unknown"}}g["default"]=a}),98);
__d("VideoChatLoggingDataContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react").createContext;b=a(null);g["default"]=b}),98);
__d("createUseMutation_DEPRECATED",["CometRelay","Promise","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useCallback;function a(a,c,e,f){return function(){var g=d("CometRelay").useRelayEnvironment();return h(function(h,i,j){return new(b("Promise"))(function(b,k){return d("CometRelay").enqueueMutation(g,{mutation:a,onCompleted:function(a,c){c&&c.length?k(c):b(a)},onError:function(a){return k([a])},optimisticResponse:c?c(h,i,j):null,optimisticUpdater:e?e(h,i,j):null,updater:f?f(h,i,j):null,variables:babelHelpers["extends"]({input:h},i)})})},[g])}}g["default"]=a}),98);
__d("XCometGroupAboutControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/groups/{idorvanity}/about/",Object.freeze({accept_recruiting_group_rules:!1,maybe_open_membership_questions:!1}),void 0);b=a;g["default"]=b}),98);
__d("GroupFeedRankingSetting",[],(function(a,b,c,d,e,f){a=Object.freeze({CHRONOLOGICAL:"CHRONOLOGICAL",RECENT_ACTIVITY:"RECENT_ACTIVITY",TOP_POSTS:"TOP_POSTS",MOST_POPULAR:"MOST_POPULAR",TOP_LISTINGS:"TOP_LISTINGS",RECENT_LISTING_ACTIVITY:"RECENT_LISTING_ACTIVITY",NEARBY_LISTINGS:"NEARBY_LISTINGS",CHRONOLOGICAL_LISTINGS:"CHRONOLOGICAL_LISTINGS",PHOTO_POSTS:"PHOTO_POSTS",VIDEO_POSTS:"VIDEO_POSTS",MEDIA_POSTS:"MEDIA_POSTS"});f["default"]=a}),66);